### ISSUE TITLE
.

### ISSUE THREAD

**Issue by FajarTheGGman** [LuckyArd110/scdefCreator#1]

**Comment by LuckyArdhika** [comment]
, ak belajar lewat script orang, aq nulis ulang bukan recode, berkat script orang yg g di enkrip w tau, dan w bisa karna setiap scrip orang, sampe akhirny w bisa buat sendiri, dan nie scrip w buat sendiri, klo w nemu bug w intip scrip nya dimana salah w? " . Jdi klo punya sc jangan di enkrip biar bisa di jadiin pembelajaran sma orang lain :)

**Comment by FajarTheGGman** [comment]
Itu sama aja lu recode Bambang, kalo mau belajar dari script orang ya script lu jangan lu publish lah pea

**Comment by FajarTheGGman** [comment]
Lu script buat sendiri apa cuma ganti credits sama author nya 🤣

**Comment by FajarTheGGman** [comment]
Aokwoakaaoka hekel kok maen spam gk punya skill lagi ya bro  🤣🤣🤣

**Comment by FajarTheGGman** [comment]
Kurang banyak bro spam nya 🤣🤣🤣
